services:
  db:
    image: postgres:16
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PORT}"
    volumes:
      - iron_calc_data:/var/lib/postgresql/data

volumes:
  iron_calc_data: